# Generated by Django 4.2.7 on 2023-11-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_nickname_alter_user_table'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nickname',
            field=models.ForeignKey(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='nickname'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
