# Generated by Django 4.2.7 on 2023-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('nickname',), name='nickname'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
