# Generated by Django 4.2.7 on 2023-11-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolling_paper',
            fields=[
                ('paper_number', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('users', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
