# Generated by Django 4.2.7 on 2023-11-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_rolling_paper_nickname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolling_paper',
            table='Paper',
        ),
    ]
